// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ChatSystem.Models;

public partial class Message
{
    [Key]
    [Column("id")]
    public int id { get; set; }

    public string message {  get; set; }
    [StringLength(150)]
    public string username {  get; set; }
    [StringLength(150)]
    public string? groupname {  get; set; }

    public DateTime time {  get; set; }
}